### ISSUE TITLE
Auth ready to be reviewed

### ISSUE THREAD

**Issue by ak415** [aazaiez/Wheelio#1]
Auth is ready to be reviewed. I tried to make edits here and there based on your feedback and what Yelp's website looks like. I will wait to hear from you before I start on the next feature.

**Comment by ak415** [comment]
Homepage and forms have been redesigned based on discussion and feedback

**Comment by s-pangburn** [comment]
Great work Akram! This is very polished! I only have a few minor points I'd like you to take care of and then you can move on to your first MVP!

- [ ] https://wheelio.herokuapp.com/#/sdlkfjdslkjflksdfjslkjf <-- This should redirect to either your splash page or your login page (This is something App Academy specifically asks for when we review)
- [x] It seems like the entire `nav` component (`welcome-login-signup`) has `cursor: pointer` on hover. Setting cursor to pointer is very important, but it's equally important that the cursor only change to a pointer on the specific clickable elements (this is a design principle). I would encourage you to change it so that the cursor only switches to pointer for each button, not the whole div.
- [x]  I understand the search bar is not functional yet obviously, but it doesn't look like most search bars around the internet, so it's not immediately clear to the user what it is for (even despite the text inside). I would style it as a pure white, slightly rounded rectangle with no outline.

That's all! Excellent work Akram, this has been one of the easiest PA Reviews I've done thus far :) Let me know when you have these done and I'll mark this as complete.

**Comment by ak415** [comment]
Thank you for the feedback. This is very helpful. 
Changes made!

**Comment by s-pangburn** [comment]
👍
